// <auto-generated />
using System;
using Etalent_C__.Net_Assessment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Etalent_C__.Net_Assessment.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20250514155820_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Etalent_C__.Net_Assessment.Models.AccountHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccountHolders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main Street, Johannesburg",
                            DateOfBirth = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            IdNumber = "8505201234088",
                            LastName = "Doe",
                            Mobile = "+27831234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Avenue, Cape Town",
                            DateOfBirth = new DateTime(1990, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            IdNumber = "9009155432084",
                            LastName = "Smith",
                            Mobile = "+27839876543"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine Road, Durban",
                            DateOfBirth = new DateTime(1978, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "peter.ngubane@example.com",
                            FirstName = "Peter",
                            IdNumber = "7802025677081",
                            LastName = "Ngubane",
                            Mobile = "+27831231234"
                        });
                });

            modelBuilder.Entity("Etalent_C__.Net_Assessment.Models.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountHolderId")
                        .HasColumnType("int");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountHolderId");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountHolderId = 1,
                            AccountNumber = 1001001001,
                            AvailableBalance = 2500.00m,
                            Name = "John's Cheque Account",
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            AccountHolderId = 1,
                            AccountNumber = 1001001002,
                            AvailableBalance = 7800.50m,
                            Name = "John's Savings",
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            AccountHolderId = 2,
                            AccountNumber = 1001002001,
                            AvailableBalance = 15000.00m,
                            Name = "Jane's Savings",
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            AccountHolderId = 2,
                            AccountNumber = 1001002002,
                            AvailableBalance = 20000.00m,
                            Name = "Jane's Fixed Deposit",
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            AccountHolderId = 3,
                            AccountNumber = 1001003001,
                            AvailableBalance = 500.00m,
                            Name = "Peter's Cheque Account",
                            Status = 1,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Etalent_C__.Net_Assessment.Models.Withdrawal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BankAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.ToTable("Withdrawals");
                });

            modelBuilder.Entity("Etalent_C__.Net_Assessment.Models.BankAccount", b =>
                {
                    b.HasOne("Etalent_C__.Net_Assessment.Models.AccountHolder", "AccountHolder")
                        .WithMany("BankAccounts")
                        .HasForeignKey("AccountHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountHolder");
                });

            modelBuilder.Entity("Etalent_C__.Net_Assessment.Models.Withdrawal", b =>
                {
                    b.HasOne("Etalent_C__.Net_Assessment.Models.BankAccount", "BankAccount")
                        .WithMany("Withdrawals")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");
                });

            modelBuilder.Entity("Etalent_C__.Net_Assessment.Models.AccountHolder", b =>
                {
                    b.Navigation("BankAccounts");
                });

            modelBuilder.Entity("Etalent_C__.Net_Assessment.Models.BankAccount", b =>
                {
                    b.Navigation("Withdrawals");
                });
#pragma warning restore 612, 618
        }
    }
}
